version: "3.8"

services:
  frontend:
    build: frontend
    depends_on:
      - backend
    expose:
      - 8501
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/frontend
      - ./frontend/data:/frontend/data
    environment:
      YT_API_KEY: null # YouTube API key
      API_HOST: backend # Name of backend service `backend`
      API_PORT: 8001
      LOG_LEVEL: INFO
      STREAM_LOGS: true

  backend:
    build: backend
    expose:
      - 8001
    ports:
      - 8001:8001
    volumes:
      - ./backend:/backend
      - ./backend/ml_models:/backend/ml_models
    environment:
      MONGODB_URL: null # MongoDB URL to connect with it
      API_PORT: 8001
      API_HOST: "0.0.0.0"
      LOG_LEVEL: INFO
      STREAM_LOGS: true

volumes:
  frontend:
  data:
  backend:
  ml_models:
